openapi: 3.0.0
info:
  description: |
   A JSON based REST API for schedule, route and bus stop information. Based on the RTPi API.
  version: "1.0.0"
  title: Galway Bus Open API
paths:
  /schedules/allSchedules:
    get:
      tags:
        - Schedules
      summary: Get PDF links for all routes
      operationId: getSchedules
      x-exegesis-controller: scheduleController
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SchedulesArray'
            application/xml:
              schema:
                $ref: '#/components/schemas/SchedulesArray'
        '400':
            description: Error retreving schedules    
  /routes/allRoutes:
    get:
      tags:
        - Routes
      summary: Gets all routes
      description: This can only be done by the logged in user.
      operationId: getAllRoutes
      x-exegesis-controller: routeController
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoutesArray'
  '/routes/{route_id}':
    get:
      tags:
        - routes
      summary: Get a list of stops for a route
      operationId: getStopsByRouteID
      x-exegesis-controller: routeController
      parameters:
        - name: route_id
          in: path
          description: The 
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StopsArray'
            application/xml:
              schema:
                $ref: '#/components/schemas/StopsArray'
        '400':
          description: Route not found with provided ID
        '404':
          description: User not found 
          
  /stops/allStops:
    get:
      tags:
        - Bus Stops
      summary: Gets all Stops
      operationId: getAllStops
      x-exegesis-controller: stopsController
      responses:
        '200':
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StopsArray'
            
          '400':
            description: Not found       
  '/stops/{stop_ref}':
    get:
      tags:
        - Bus Stops
      summary: Get user by user name
      operationId: getStopsByStopRef
      x-exegesis-controller: stopsController
      parameters:
        - name: stop_ref
          in: path
          description: Reference number of a particular stop
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StopsArray'
            application/xml:
              schema:
                $ref: '#/components/schemas/StopsArray'
        
        '404':
          description: Stop not found   
  /stops/nearby:
    get:
      tags:
        - Bus Stops
      summary: Gets all nearby stops
      description: This can only be done by the logged in user.
      operationId: getNearbyStops
      parameters:
        - in: query
          name: longitude
          schema:
            type: string
          description: Coordinate
        - in: query
          name: latitude
          schema:
            type: string
          description: Coordinate
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StopsArray'

components:
  schemas:
    Bus_Stop:
      type: object
      properties:
        stop_id:
          type: integer
          format: int32
        stop_full_name:
          type: string
        stop_short_name:
          type: integer
          format: int32
        longitude:
          type: string
        latitude:
          type: string
          
        in_galway:
          type: boolean
          default: false
      xml:
        name: Order
    StopsArray:
      type: object
      properties:
        stops:
          type: array
          items:
            $ref: '#/components/schemas/Bus_Stop'
    RoutesArray:
      type: object
      properties:
        routes:
          type: array
          items:
            $ref: '#/components/schemas/Route'
  
    Route:
      type: object
      properties:
        route_id:
          type: integer
          format: int32
        full_route_name:
          type: string
        short_route_name:
          type: string
        
      xml:
        name: Route
    SchedulesArray:
      type: object
      properties:
        schedules:
          type: array
          items:
            $ref: '#/components/schemas/Schedule'
    Schedule:
      type: object
      properties:
        route_id:
          type: integer
        route_name:
          type: string
        pdf_link:
          type: string
          
      xml:
        name: Tag
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
    