openapi: 3.0.0
info:
  description: |
   A JSON based REST API 
  version: "1.0.0"
  title: Galway Bus
  termsOfService: 'http://swagger.io/terms/'
paths:
  /schedules/allSchedules:
    get:
      tags:
        - schedules
      summary: Get PDF links for all routes
      operationId: getSchedules
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SchedulesArray'
            application/xml:
              schema:
                $ref: '#/components/schemas/SchedulesArray'
       

components:
  schemas:
    Bus_Stop:
      type: object
      properties:
        stop_id:
          type: int
          format: int64
        stop_full_name:
          type: string
        stop_short_name:
          type: integer
          format: int32
        longitude:
          type: string
        latitude:
          type: string
          
        in_galway:
          type: boolean
          default: false
      xml:
        name: Order
    StopsArray:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Bus_Stop'
    RoutesArray:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Route'
  
    Route:
      type: object
      properties:
        route_id:
          type: integer
          format: int64
        full_route_name:
          type: string
        short_route_name:
          type: string
        
      xml:
        name: Route
    SchedulesArray:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Schedule'
    Schedule:
      type: object
      properties:
        route_id:
          type: integer
        route_name:
          type: string
        pdf_link:
          type: string
          
      xml:
        name: Tag
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
    